version: '3.1'
services:
  mongo:
    image: mongo
    container_name: myMongoDb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db 
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin


volumes:
  mongodb: