version: '3.1'
services:
  mongodb:
    image: mongo
    container_name: container_mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db 
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  product.api:
    image: product_api_image
    container_name: container_product_api
    build:
      context: .
      dockerfile: Services/Product/Ttar.Services.Product/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 5011:80


volumes:
  mongodb: